config/routes.rb
Rails.application.routes.draw do
  # resources :courses
  # resources :students
  get "/students", to: "students#index", as: "students"
  get "/students/new", to: "students#new", as: "new_student"
  post "/students", to: "students#create"
  get "/students/:id", to: "students#show", as: "student"
  get "/students/:id/edit", to: "students#edit", as: "edit_student"
  patch "/students/:id", to: "students#update"
  delete "/students/:id", to: "students#destroy"

  get "/courses", to: "courses#index", as: "courses"
  get "/courses/new", to: "courses#new", as: "new_course"
  post "/courses", to: "courses#create"
  get "/courses/:id", to: "courses#show", as: "course"
  get "/courses/:id/edit", to: "courses#edit", as: "edit_course"
  patch "/courses/:id", to: "courses#update"
  delete "/courses/:id", to: "courses#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
    has_many :student_courses
    has_many :students, through: :student_courses
end

app/models/student.rb
class Student < ApplicationRecord
    has_many :student_courses
    has_many :courses, through: :student_courses
end

app/models/student_course.rb
class StudentCourse < ApplicationRecord
    belongs_to :student
    belongs_to :course
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
    
    def index
        @courses = Course.all
    end

    def show
        @course = Course.find(params[:id])
    end

    def new
        @course = Course.new
    end

    def create
        @course = Course.create(course_params)
        redirect_to course_path(@course)
    end

    def edit
        @course = Course.find(params[:id])
    end

    def update
        @course = Course.find(params[:id])
        @course.update(course_params)
        redirect_to course_path(@course)
    end

    def destroy
        @course = Course.find(params[:id])
        @course.destroy
        redirect_to courses_path
    end

    private
    def course_params
        params.require(:course).permit(:name, :age)
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

    def index
        @students = Student.all
    end

    def show
        @student = Student.find(params[:id])
        @courses = @student.courses
    end

    def new
        @student = Student.new
    end

    def create
        @student = Student.create(student_params)
        redirect_to student_path(@student)
    end

    def edit
        @student = Student.find(params[:id])
    end

    def update
        @student = Student.find(params[:id])
        @student.update(student_params)
        redirect_to student_path(@student)
    end

    def destroy
        @student = Student.find(params[:id])
        @student.destroy
        redirect_to students_path
    end

    private
    def student_params
        params.require(:student).permit(:name, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PairingGroup1</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/students/edit.html.erb
<h2> Edit a Student </h2>

<%= form_for @student do |f| %>
<%=f.label :name, "Please Update a Name"%>
<%=f.text_field :name %>
<%=f.label :age, "Please Update Your Age"%>
<%=f.number_field :age %>
<%=f.submit%>
<%end%>

app/views/students/index.html.erb
<h1>All Students</h1>
<ul>
    <% @students.each do |student|%>
        <li>
        <%=link_to student.name, student_path(student)%>
        </li>
    <%end%>
</ul>

<%=link_to "Create a New Student", new_student_path%>

app/views/students/new.html.erb
<h2> Create a New Student </h2>

<%= form_for @student do |f| %>
<%=f.label :name, "Please Enter a Name"%>
<%=f.text_field :name %>
<%=f.label :age, "Please Enter Your Age"%>
<%=f.number_field :age %>
<%=f.submit%>
<%end%>

app/views/students/show.html.erb
<h2> Here is <%=@student.name%> </h2>
<ul>
<% @courses.each do |course|%>
    <li>
        <%=link_to course.name, course_path(course)%>  
    </li>
<%end%>
</ul>

<%=link_to "Edit to your Info", edit_student_path(@student)%>
<%=button_to "Destroy Yourself :(", student_path(@student), method "delete"%>